cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'


urlpatterns = [  
    path('seu-carrinho/', views.CartView.as_view(), name='view_cart'),
    path('adicionar/', views.AddProductCartView.as_view(), name='add_product'),
    path('limpar-carrinho/', views.CleanCartView.as_view(), name='clean_cart'),
]

checkout/urls.py
from django.urls import path
from checkout.views import OrderConfirmationView, OrdersView, OrderDetail

app_name = 'checkout'


urlpatterns = [  
    path('pedido-confirmado/', OrderConfirmationView.as_view(), name='order-confir'),
    path('seus-pedidos/', OrdersView.as_view(), name='orders'),
    path('detalhes/<int:pk>/', OrderDetail.as_view(), name='order_view'),
]

core/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('carrinho/', include('cart.urls')),
    path('perfil/', include('accounts.urls')),
    path('perfil/', include('allauth.urls')),
    path('pedidos/', include('checkout.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store'


urlpatterns = [  
    path('', views.IndexView.as_view(), name='index'),
    path('adm/', views.AdminDashboardView.as_view(), name='admin_dashboard'),
    path('add/', views.ProductCreateView.as_view(), name='add_product'),

]

cart/models.py
from django.db import models
from django.conf import settings

from store.models import Product


class Cart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    session_key = models.CharField(max_length=40, null=True, blank=True)
    
    @property
    def get_cart_total(self):
        total = sum(prod.get_cart_item_subtotal for prod in self.prods.all())
        return total

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, related_name='prods', on_delete=models.DO_NOTHING)
    product = models.ForeignKey(Product, related_name='items', on_delete=models.DO_NOTHING, null=True, blank=True)
    quantity = models.PositiveIntegerField(default=0)
    
    @property
    def get_cart_item_subtotal(self):
        return self.product.price * self.quantity

cart/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse

from django.views.generic.list import ListView
from django.views.generic import (
    CreateView, 
    TemplateView, 
    View,
    DeleteView,
    FormView,
    DetailView,
)

from store.models import Product
from checkout.forms import OrderCheckoutForm
from checkout.models import Order, OrderItem
from .models import Cart, CartItem


class CartView(DetailView, FormView):
    template_name = 'cart/items.html'
    form_class = OrderCheckoutForm
    success_url = reverse_lazy('checkout:order-confir')

    def get_object(self):
        if self.request.user.is_authenticated:
            return Cart.objects.filter(user=self.request.user).last()
        elif self.request.user.is_anonymous:
            return Cart.objects.filter(session_key=self.request.session.session_key).last() 
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart = self.get_object() if self.get_object() else None
        context['items'] = cart.prods.all() if cart else None
        context['form'] = self.get_form()
        return context


class CleanCartView(DeleteView):
    model = Cart
    success_url = reverse_lazy('cart:view_cart')

    def get_object(self, queryset=None):
        return Cart.objects.get(session_key=self.request.session.session_key)

    def delete(self, request, *args, **kwargs):
        cart = self.get_object()
        cart.delete()
        success_url = self.get_success_url()
        return redirect(success_url)

class AddProductCartView(View):
    def post(self, request, *args, **kwargs):
        id = request.POST.get('product_id')
        product = Product.objects.get(id=id)

        if request.user.is_authenticated:
            cart, created = Cart.objects.get_or_create(user=request.user)
        else:
            session_key = request.session.session_key
            if not session_key:
                request.session.create()
                session_key = request.session.session_key
            cart, created = Cart.objects.get_or_create(session_key=session_key)

        cart_item, created = CartItem.objects.get_or_create(cart=cart, product=product)
        cart_item.quantity += 1
        cart_item.save()
        return redirect('cart:view_cart')

templates/cart/items.html
{% extends 'layouts/base.html' %} 

{% load django_bootstrap5 grid_tags static %}

{% block title %}Carrinho{% endblock %}


{% block content %}
<!-- Cart Section -->
<section id="cart-list-items">
  {% container %}
    {% if cart %}
      {% row 'd-flex justify-content-center mx-4 mt-4' %}
        {% col 'col-12 col-md-7' %}
          <!-- Cart Items List -->
          <ul class="list-group list-group-flush shadow-lg">
            {% for item in items %}                
            <li class="list-group-item border-1 rounded-0">
              <div class="row align-items-center">
                <div class="col-3">
                  <!-- Img -->
                  {% if item.product.category == 'A' %}
                    <img src="{% static 'img/agua.png' %}" class="card-img-top" height="180">
                  {% endif %}
                  {% if item.product.category == 'G' %}
                    <img src="{% static 'img/gas.png' %}" class="card-img-top" height="180">
                  {% endif %}
                </div>
                <div class="col">
                  <!-- Product Description -->
                  <div class="d-flex mb-2 fw-bold">
                    <h5 class="text-primary">{{ item.product.description }}</h5>
                    <span class="ms-auto">{{ item.product.price }}</span>
                  </div>
                  <!-- Form Footer -->
                  <div class="d-flex align-items-end">
                    <p class="text-primary mt-2 mb-0 pb-2">Qtd:{{ item.quantity }} </p>
                  </div>
                </div>
              </div>
            </li>
            {% endfor %}
          </ul>
          {% row 'text-end' %}
            {% col 'col-12 my-2' %} 
              <form action="{% url 'cart:clean_cart' %}" method="post">
                {% csrf_token %}
                {% bootstrap_button button_class="btn btn-link px-0" button_type="submit" content="Limpar Carrinho" %}
              </form>
            {% endcol %}
          {% endrow %}
        {% endcol %}
        {% col 'col-12 col-md-5 col-lg-4 offset-lg-1' %}
          <div class="card text-center text-primary border-1 rounded-0 shadow-lg mb-4">
            <div class="card-body">
              <h4 class="card-title fw-bold my-2 pb-2">Resumo</h4>
                <ul class="list-group list-group-flush">
                  {% for item in items %}                
                    <li class="list-group-item d-flex text-primary">
                      <span>{{ item.product.description }}</span>
                      <span class="ms-auto fs-sm">R$ {{ item.get_cart_item_subtotal }}</span>
                    </li>
                  {% endfor %}
                  <li class="list-group-item d-flex fs-lg fw-bold my-2">
                    <span>Subtotal:</span>
                    <span class="ms-auto fs-sm">R$ {{ cart_total|floatformat:2 }}
                    </span>
                  </li>
                </ul>

                <hr class="my-2">          
                <div class="mt-2">
                  <form method="POST" action="{% url 'checkout:order-confir' %}">
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    <div class="mb-3">
                      {{ form.is_shipping }}
                    </div>
                    <div class="mb-3 text-start" id="shipping-address-field">
                      {% bootstrap_field form.shipping_address label_class="mb-0" placeholder="Rua..." %}
                    </div>
                    <div class="mb-3 text-start">
                      {% bootstrap_field form.payment_method label_class="mb-0" %}
                    </div>
                    <div class="mb-3">
                      {% bootstrap_field form.observation show_label=False placeholder="Observação..." %}
                    </div>
                    <div class="mb-3">
                      {% bootstrap_button button_type="submit" button_class="btn btn-primary w-100 shadow-lg rounded-0 mt-4 mb-2" content="Confirmar" %} 
                    </div>
                  </form>
                </div>
              <a class="btn btn-link px-0 text-primary" href="{% url 'store:index' %}">Continuar Comprando</a>
            </div>
          </div>
        {% endcol %}
      {% endrow %}
    {% else %}
    <!-- Null Cart -->
      {% row 'd-flex justify-content-center mt-5' %}
        {% col 'col-md-8 my-2 text-center' %}
          <img src="{% static 'icon/cart-x.svg' %}" width="64" height="64" alt="Carrinho Vazio">         
          <h2 class="mt-2">Seu carrinho está vazio!</h2>
          <small>Você ainda não possui itens no seu carrinho.</small>
        {% endcol %}
      {% endrow %}  
      {% row 'd-flex justify-content-center mb-5' %}
        {% col 'col-md-8 my-2 text-center' %}
          <a class="btn btn-primary text-center w-25" href="{% url 'store:index' %}">Adicionar</a>
        {% endcol %}
      {% endrow %}
    {% endif %}
  {% endcontainer %}
{% endblock content %}
</section>