accounts/urls.py
from django.urls import path, include

from allauth.account.views import LogoutView as LogoutOnGetView

from accounts.views import LoginOnGetView, CustomSignupView

app_name = 'accounts'


urlpatterns = [
    path('cadastrar/', CustomSignupView.as_view(), name='signup'),
    path('entrar/', LoginOnGetView.as_view(), name='login'),
    path('sair/', LogoutOnGetView.as_view(), name='logout'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'


urlpatterns = [  
    path('seu-carrinho/', views.CartView.as_view(), name='view_cart'),
    path('adicionar/', views.AddProductCartView.as_view(), name='add_product'),
    path('limpar-carrinho/', views.CleanCartView.as_view(), name='clean_cart'),
]

checkout/urls.py
from django.urls import path
from checkout.views import OrderConfirmationView, OrdersView, OrderDetail

app_name = 'checkout'


urlpatterns = [  
    path('pedido-confirmado/', OrderConfirmationView.as_view(), name='order-confir'),
    path('seus-pedidos/', OrdersView.as_view(), name='orders'),
    path('detalhes/<int:pk>/', OrderDetail.as_view(), name='order_view'),
]

core/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('carrinho/', include('cart.urls')),
    path('perfil/', include('accounts.urls')),
    path('perfil/', include('allauth.urls')),
    path('pedidos/', include('checkout.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store'


urlpatterns = [  
    path('', views.IndexView.as_view(), name='index'),
    path('adm/', views.AdminDashboardView.as_view(), name='admin_dashboard'),
    path('add/', views.ProductCreateView.as_view(), name='add_product'),

]

templates/partials/_footer.html
{% load grid_tags static %}

<!-- Footer -->
{% container 'd-flex justify-content-around mt-2' %}
  {% row 'my-5 row-cols-2 row-cols-sm-2 row-cols-md-4' %}
    {% col %}
      <a href="{% url 'store:index' %}" class="mb-3 link-body-emphasis text-decoration-none">
      <img src="{% static 'img/logo.png' %}" width="96" height="96" alt="" class="logo-footer">
      </a>
    {% endcol %}

    {% col %}
      <h5>Contato</h5>
      <ul class="nav flex-column">
        <li class="nav-item mb-2"><a href="https://web.whatsapp.com" target="_blank" class="nav-link p-0 text-secondary"><i class="fa-brands fa-whatsapp"></i>(48) 11111-9999</a></li>
        <li class="nav-item mb-2"><a href="mailto:email@admin.com" class="nav-link p-0 text-secondary"><i class="fa-solid fa-envelope-circle-check"></i>email@admin.com</a></li>
      </ul>
    {% endcol %}

    {% col %}
      <h5>Endereço</h5>
      <small class="text-secondary">Rua Teste, Los Angeles-SJ</small>
    {% endcol %}

    {% col %}
      <h5>Horários</h5>
      <small class="text-secondary">De Segunda a Sabádo, das 11h30 às 23h</small>
    {% endcol %}

  {% endrow %}
{% endcontainer %}

<div class="text-center text-secondary border-top border-primary-subtle my-2">  
  <p class="mb-0 mt-4">Desenvolvido por, <a href="https://www.vivasoft.dev.br/" target="_blank">www.vivasoft.dev.br
  </p>
    <small>Siga-nós<a href="https://www.instagram.com/vivasoft.dev/" target="_blank">
      <img src="{% static 'icon/instagram.svg' %}" width="18" height="18" class="ms-1">
    </a>
  </small>
</div>

templates/partials/_navbar.html
{% load grid_tags static %}


{% container %}
<!-- NavBar -->
  <nav class="navbar navbar-expand-lg bg-white sticky-top mx-4" aria-label="Template Navbar">
    <a class="navbar-brand text-primary" href="{% url 'store:index' %}">
      <img src="{% static 'img/logo.png' %}" width="96" height="96">
      Disk Delivery
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#MynavbarHeader" aria-controls="MynavbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="MynavbarHeader">
      <ul class="navbar-nav ms-auto ">
          <li class='nav-item'>
            <a class='nav-link text-primary' href="{% url 'cart:view_cart' %}">
              <i class="fa-solid fa-cart-shopping"></i> Carrinho
            </a>
          </li>
        {% if request.user.is_authenticated %}
          <li class='nav-item'>
            <a class='nav-link text-primary' href="{% url 'checkout:orders' %}">
              <i class="fa-solid fa-address-card"></i> {{request.user.email}}
            </a>
          </li>
          <li class='nav-item'>
            <a class='nav-link text-primary' href="{% url 'accounts:logout' %}">
              <i class="fa-solid fa-right-from-bracket"></i> Sair
            </a>
          </li>
        {% else %}
           <li class='nav-item'>
            <a class='nav-link text-primary' href="{% url 'accounts:signup' %}">
              <i class="fa-solid fa-user-plus"></i> Cadastrar
            </a>
          </li>
          <li class='nav-item'>
            <a class='nav-link text-primary' href="{% url 'accounts:login' %}">
              <i class="fa-solid fa-right-to-bracket"></i> Entrar
            </a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>
{% endcontainer %}