cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'


urlpatterns = [  
    path('seu-carrinho/', views.CartView.as_view(), name='view_cart'),
    path('adicionar/', views.AddProductCartView.as_view(), name='add_product'),
    path('limpar-carrinho/', views.CleanCartView.as_view(), name='clean_cart'),
]

core/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('carrinho/', include('cart.urls')),
    path('perfil/', include('accounts.urls')),
    path('perfil/', include('allauth.urls')),
    path('pedidos/', include('checkout.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/index.html
{% extends 'layouts/base.html' %} 

{% load django_bootstrap5 grid_tags static %}

{% block title %}Disk Água e Gás{% endblock %}


{% block content %}
<!-- Product List Section -->
<section id="products">
  {% container %}
    {% if product_list %}
      {% row 'd-flex justify-content-center mt-4' %}
        {% for product in product_list %}
          {% col 'col-12 col-sm-10 col-md-8 col-lg-4' %}
            <div class="card w-md-50 w-lg-75 mx-auto shadow mb-4" href="#">
              {% if product.category == 'A' %}
                <img src="{% static 'img/agua.png' %}" class="card-img-top" height="320">
              {% endif %}
              {% if product.category == 'G' %}
                <img src="{% static 'img/gas.png' %}" class="card-img-top" height="320">
              {% endif %}
              <div class="card-body">
                <h5 class="card-title">{{ product.description }}</h5>
                <p class="card-text">{{ product.price }}</p>
                <div class="card-btn text-center">
                  <form method="POST" action="{% url 'cart:add_product' %}">
                    {% csrf_token %}
                    <input type="hidden" name="product_id" value="{{ product.id }}">
                    {% bootstrap_button button_class="btn btn-primary w-50" button_type="submit" content="Comprar" %}
                  </form>
                </div>
              </div>
            </div>
          <hr class="my-2">
          {% endcol %}  
        {% endfor %}
      {% endrow %}
    {% else %}
      {% row 'd-flex justify-content-center mt-5' %}
        {% col 'col-md-8 my-2 text-center text-primary' %}
          <img src="{% static 'icon/cart-x.svg' %}" width="64" alt="Sem Produtos">         
          <h2 class="mt-2"> Eyyy :(</h2>
          <small>Ainda não foi cadastrado produtos nesta loja!!!</small>
        {% endcol %}
      {% endrow %}
    {% endif %}
  {% endcontainer %}
</section>
{% endblock content %}