cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'


urlpatterns = [  
    path('seu-carrinho/', views.CartView.as_view(), name='view_cart'),
    path('adicionar/', views.AddProductCartView.as_view(), name='add_product'),
    path('limpar-carrinho/', views.CleanCartView.as_view(), name='clean_cart'),
]

checkout/urls.py
from django.urls import path
from checkout.views import OrderConfirmationView, OrdersView, OrderDetail

app_name = 'checkout'


urlpatterns = [  
    path('pedido-confirmado/', OrderConfirmationView.as_view(), name='order-confir'),
    path('seus-pedidos/', OrdersView.as_view(), name='orders'),
    path('detalhes/<int:pk>/', OrderDetail.as_view(), name='order_view'),
]

core/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('carrinho/', include('cart.urls')),
    path('perfil/', include('accounts.urls')),
    path('perfil/', include('allauth.urls')),
    path('pedidos/', include('checkout.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store'


urlpatterns = [  
    path('', views.IndexView.as_view(), name='index'),
    path('adm/', views.AdminDashboardView.as_view(), name='admin_dashboard'),
    path('add/', views.ProductCreateView.as_view(), name='add_product'),

]

checkout/models.py
from django.db import models
from django.conf import settings

from store.models import Product


class Order(models.Model):
    ORDER_STATUS  = [
        ('received','Recebido'),
        ('inprogress','Preparando'),
        ('delivered','Entregue'),
        ('canceled','Cancelado'),
    ]
    
    PAYMENT_METHOD_CHOICES = [
        ('csh', 'Dinheiro'),
        ('cre', 'Crédito'),
        ('deb', 'Débito'),
        ('pix','Pix'),
    ]
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING)
    total = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    observation = models.TextField(blank=True, null=True)
    is_shipping = models.BooleanField(default=False)
    shipping_address = models.CharField(max_length=25, blank=True, null=True, default='')
    payment_method = models.CharField(max_length=3, choices=PAYMENT_METHOD_CHOICES, default='csh')
    status = models.CharField(max_length=10, choices=ORDER_STATUS, default='received')

    class Meta:
        ordering = ['-created_at']

        
class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    quantity = models.PositiveIntegerField()

checkout/forms.py
from django import forms
from .models import Order

from django.utils.translation import gettext_lazy as _
from django_bootstrap5.widgets import RadioSelectButtonGroup

 
class OrderCheckoutForm(forms.ModelForm):
    SHIPPING_CHOICES = [
        (True, 'Entregar'),
        (False, 'Buscar')
    ]

    is_shipping = forms.ChoiceField(choices=SHIPPING_CHOICES, widget=RadioSelectButtonGroup)

    class Meta:
        model = Order
        fields = ['is_shipping', 'shipping_address', 'payment_method', 'observation']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['is_shipping'].initial = True
        self.fields['is_shipping'].widget.attrs.update({'class': 'form-check-input shadow'})
        self.fields['shipping_address'].widget.attrs.update({'class': 'form-control shadow'})
        self.fields['payment_method'].widget.attrs.update({'class': 'form-control shadow'})
        self.fields['observation'].widget.attrs.update({'class': 'form-control shadow'})

        self.fields['shipping_address'].label = _('Endereço')
        self.fields['payment_method'].label = _('Pagamento')

    def clean(self):
        cleaned_data = super().clean()
        is_shipping = cleaned_data.get('is_shipping') == 'True'
        shipping_address = cleaned_data.get('shipping_address')
        payment_method = cleaned_data.get('payment_method')
        observation = cleaned_data.get('observation')

        if is_shipping:
            self.fields['shipping_address'].required = True
            if not shipping_address:
                self.add_error('shipping_address', _('Informar endereço de entrega!'))
        else:
            self.fields['shipping_address'].required = False

        return cleaned_data

checkout/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy, reverse


from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView

from cart.models import Cart, CartItem

from .models import Order, OrderItem

class OrderConfirmationView(LoginRequiredMixin, CreateView):
    model = Order
    template_name = 'checkout/order_confirmation.html'
    fields = []
    context_object_name = 'order'
    success_url = reverse_lazy('checkout:order-confir')

    def get_cart(self):
        return Cart.objects.filter(user=self.request.user).last()

    def get_object(self):
        order = Order.objects.filter(user=self.request.user).last()
        if order:
            return order
        
        cart = self.get_cart()
        if not cart:
            return None

        order = Order.objects.create(
            user=self.request.user,
            total=sum(item.product.price * item.quantity for item in cart.prods.all()),
            shipping_address=form.cleaned_data['shipping_address'] if form.cleaned_data['is_shipping'] == 'True' else None,
            payment_method=form.cleaned_data['payment_method'],
            observation=form.cleaned_data['observation'],
            is_shipping=form.cleaned_data['is_shipping'],
        )  

        for cart_item in cart.prods.all():
            OrderItem.objects.create(
                order=order,
                product=cart_item.product,
                quantity=cart_item.quantity,
            )
        cart.prods.all().delete()
        cart.delete()
        
        return order

    def form_valid(self, form):
        self.object = self.get_object()
        if not self.object:
            return redirect('cart:view_cart')

        return super().form_valid(form)


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        order = self.get_object()
        context['order'] = order
        context['items'] = order.items.all() if order else None
        return context


class OrdersView(LoginRequiredMixin, ListView):
    template_name = 'checkout/orders.html'
    context_object_name = 'orders'

    def get_queryset(self):
        if self.request.user.is_superuser:
            return Order.objects.all()
        else:
            return Order.objects.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        orders = self.get_queryset()

        for order in orders:
            order.order_items = OrderItem.objects.filter(order=order)

        return context

class OrderDetail(DetailView):
    model = Order
    template_name = 'checkout/order.html'
    context_object_name = 'order'

templates/checkout/order.html
{% extends 'layouts/base.html' %}

{% load grid_tags static %}

{% block title %}Detalhes do Pedido{% endblock %}


{% block content %}
<!-- Order Section -->
  
  <div class="card mb-4 shadow">
    <div class="card-body pb-0">
      <div class="card">
        <div class="card-body p-4 pb-2">
          {% row %}
            {% col 'col-6 col-lg-3' %}
              <h6 class="text-muted">Código</h6>
              <p class="mb-lg-0 fs-sm fw-bold">#{{ order.id }}</p>
            {% endcol %}

            {% col 'col-6 col-lg-3' %}
              <h6 class="text-muted">Data</h6>
              <p class="mb-lg-0 fs-sm fw-bold">{{ order.created_at }}</p>
            {% endcol %}
            
            {% col 'col-6 col-lg-3' %}
              <h6 class="text-muted">Status</h6>
              <p class="mb-lg-0 fs-sm fw-bold">{{ order.status }}</p>
            {% endcol %}
            
            {% col 'col-6 col-lg-3' %}
              <h6 class="text-muted">Valor Total:</h6>
              <p class="mb-lg-0 fs-sm fw-bold">{{ order.total }}</p>
            {% endcol %}
          {% endrow %}
        </div>
      </div>
    </div>
    <div class="card-footer">
      {% row 'd-flex align-items-center' %}
        <!-- Order Items -->
        {% col 'col-12 col-lg-6' %}
          {% row 'd-flex justify-content-evenly m-4' %}
            <h3>Items:</h3>
            {% for item in order.order_items %}
              <!-- Img -->
              {% col 'col-4' %}
                <img class="img-fluid" src="{{ item.product.photo_main.url }}" width="128" height="128" alt="Carrinho Item Imagem">
              {% endcol %}
            {% endfor %}
          {% endrow %}
        {% endcol %}
        <!-- Buttom Detail -->
        {% col 'col-12 col-lg-6' %}
          {% row 'justify-content-center m-2' %}
            <a class="btn btn-dark w-25" href="#">Preparando</a>
            <a class="btn btn-dark w-25" href="#">Entregue</a>
            <a class="btn btn-dark w-25" href="#">Cancelado</a>
          {% endrow %}
        {% endcol %}
      {% endrow %}
    </div>
  </div>

{% endblock content %}

templates/checkout/order_confirmation.html
{% extends 'layouts/base.html' %}

{% load grid_tags static %}

{% block title %}Pedido Confirmado!{% endblock %}


{% block content %}
<!-- Order Section -->
<section id="order" class="py-5">
  {% container %}
    {% row 'justify-content-center' %}  
      {% col 'col-12 col-md-10 col-lg-8 col-xl-6 text-center' %}
        <!-- Img SVG -->
        <img src="{% static 'icons/cart-check.svg' %}" width="128" height="128" alt="Pedido Confirmado" class="img-fluid" >

        <h2 class="mt-4 mb-2">Pedido Confirmado!!!</h2>
        <p>Obrigado! Seu pedido está sendo preparado.</p>
        
        <div class="card mb-4 shadow">
          <div class="card-body pb-0">
            <div class="card">
              <div class="card-body p-4 pb-2">
                {% row %}
                  {% col 'col-6 col-lg-3' %}
                    <h6 class="text-muted">Código</h6>
                    <p class="mb-lg-0 fs-sm fw-bold">#{{ order.id }}</p>
                  {% endcol %}

                  {% col 'col-6 col-lg-3' %}
                    <h6 class="text-muted">Data</h6>
                    <p class="mb-lg-0 fs-sm fw-bold">{{ order.created_at }}</p>
                  {% endcol %}
                  
                  {% col 'col-6 col-lg-3' %}
                    <h6 class="text-muted">Status</h6>
                    <p class="mb-lg-0 fs-sm fw-bold">{{ order.status }}</p>
                  {% endcol %}
                  
                  {% col 'col-6 col-lg-3' %}
                    <h6 class="text-muted">Valor Total:</h6>
                    <p class="mb-lg-0 fs-sm fw-bold">{{ order.total }}</p>
                  {% endcol %}
                {% endrow %}
              </div>
            </div>
          </div>
          <div class="card-footer">
            {% row 'd-flex align-items-center' %}
              <!-- Order Items -->
              {% col 'col-12 col-lg-6' %}
                
                <ol>
                  {% for item in order.items.all %}
                    
                      {% row %}
                        
                        <table class="table">
                          <tbody>
                            <tr>
                              <td>
                                  <img class="img-fluid" src="{{ item.pizza.photo_main.url }}" width="32" height="32" alt="Carrinho Item Imagem">
                              

                              </td>

                              <td>
                                  <li>
                                      
                                    {{ item.pizza.name }}
                                    
                                  </li>

                              </td>


                            </tr>
                          </tbody>
                        </table>
                            


                      {% endrow %}
                    
                  {% endfor %}
                </ol>
              {% endcol %}
              <!-- Buttom Detail -->
              {% col 'col-12 col-lg-6' %}
                {% row 'justify-content-center m-2' %}
                  <a class="btn btn-dark w-50" href="#}">Detalhes</a>
                {% endrow %}
              {% endcol %}
            {% endrow %}
          </div>
        </div>
        
        <a class="btn btn-outline-primary w-50 my-2" href="#">Meus Pedidos</a>
      {% endcol %}
    {% endrow %}
  {% endcontainer %}
</section>
{% endblock content %}

templates/checkout/orders.html
{% extends 'layouts/base.html' %}

{% load grid_tags static %}

{% block title %}Painel de Usuário{% endblock %}


{% block content %}
<!-- Orders View -->
{% if request.user.is_superuser %}
<!-- Admin Section -->
<div class="d-flex align-items-stretch">
  {% container 'px-lg-4 px-xl-5' %}
  
    <section class="mb-3 mb-lg-5" id="admin-dashboard">
      
      <!-- Add Product --> 
      <div class="text-center">            
        <a href="{% url 'store:add_product' %}" class="btn btn-dark w-100">Adicionar Produto</a>
      </div>
      <!-- Main -->
        {% row 'mx-md-0 mx-lg-4 px-md-0 px-lg-2 mt-4' %}
          <h2>Lucas</h2>
          <div class="table-responsive p-4">
            <table class="table table-hover shadow rounded">
              <thead class="table-light">
                  <tr>
                      <th scope="col">ID</th>
                      <th scope="col">Observation</th>
                      <th scope="col">Shipping</th>
                      <th scope="col">Payment Method</th>
                      <th scope="col">Status</th>
                      <th scope="col">Total</th>
                  </tr>
              </thead>
              <tbody class="table-group-divider">
                  {% for order in orders %}
                  <tr scope="row">
                    <td><a href="{% url 'checkout:order_view' order.id %}">{{ order.id }}</a></td>
                    <td>{{ order.observation }}</td>
                    <td>{{ order.is_shipping|yesno:"Sim,Não" }}</td>
                    <td>{{ order.get_payment_method_display }}</td>
                    <td>{{ order.get_status_display }}</td>
                    <td>R$ {{ order.total }}</td>
                  </tr>
                  {% endfor %}
              </tbody>
            </table>
          </div>
        {% endrow %}


    </section>
  {% endcontainer %}
</div>



{% else %}
<!-- User Section -->
<section id="user-dashboard" class="py-5">
  {% container %}
    <!-- Main -->
    {% row 'row-cols-1 row-cols-md-2 justify-content-center' %}
      <!-- User Card -->
      {% col 'col-12 col-md-3' %}
        <div class="card border shadow">      
          <div class="card-header text-center py-4">
            <img src="{{ user.photo.url }}" class="card-img-top img-fluid rounded-circle shadow-lg border border-2 border-black" style="width: 96px; height: 96px;" alt="Avatar">
            <h4 class="mb-0 mt-2">{{ user.first_name}}</h4>
            <p class="card-text text-muted"><small class="text-body-secondary">{{ user.email }}</small></p>
          </div>
          <div class="card-body">
            <nav class="list-group">
              <a class="list-group-item d-flex justify-content-between align-items-center text-decoration-none" href="{% url 'checkout:orders' %}">
                <span>
                  <img src="{% static 'icons/bag-check.svg' %}" class="me-2" width="24" height="24" alt="">
                  Seus Pedidos
                </span>
              </a>
              <a class="list-group-item d-flex justify-content-between align-items-center text-decoration-none" href="#">
                <span>
                  <img src="{% static 'icons/person-gear.svg' %}" class="me-2" width="24" height="24" alt="">
                  Seu Perfil
                </span>               
              </a>
            </nav>
          </div>
        </div>
      {% endcol %}
      <!-- Orders Card -->
      {% col 'col-12 col-md-9' %}
        {% if orders %}
          {% for order in orders %}
            <div class="card mb-4 shadow">
              <div class="card-body pb-0">
                <div class="card">
                  <div class="card-body p-4 pb-2">
                    {% row %}
                      {% col 'col-6 col-lg-3' %}
                        <h6 class="text-muted">Código</h6>
                        <p class="mb-lg-0 fs-sm fw-bold">#{{ order.id }}</p>
                      {% endcol %}

                      {% col 'col-6 col-lg-3' %}
                        <h6 class="text-muted">Data</h6>
                        <p class="mb-lg-0 fs-sm fw-bold">{{ order.created_at }}</p>
                      {% endcol %}
                      
                      {% col 'col-6 col-lg-3' %}
                        <h6 class="text-muted">Status</h6>
                        <p class="mb-lg-0 fs-sm fw-bold">{{ order.status }}</p>
                      {% endcol %}
                      
                      {% col 'col-6 col-lg-3' %}
                        <h6 class="text-muted">Valor Total:</h6>
                        <p class="mb-lg-0 fs-sm fw-bold">{{ order.total }}</p>
                      {% endcol %}
                    {% endrow %}
                  </div>
                </div>
              </div>
              <div class="card-footer">
                {% row 'd-flex align-items-center' %}
                  <!-- Order Items -->
                  {% col 'col-12 col-lg-6' %}
                    
                    <ol>
                      {% for item in order.order_items %}
                        
                          {% row %}
                            
                            <table class="table">
                              <tbody>
                                <tr>
                                  <td>
                                      <img class="img-fluid" src="{{ item.pizza.photo_main.url }}" width="32" height="32" alt="Carrinho Item Imagem">
                                  

                                  </td>

                                  <td>
                                      <li>
                                          
                                        {{ item.pizza.name }}
                                        
                                      </li>

                                  </td>


                                </tr>
                              </tbody>
                            </table>
                                


                          {% endrow %}
                        
                      {% endfor %}
                    </ol>
                  {% endcol %}
                  <!-- Buttom Detail -->
                  {% col 'col-12 col-lg-6' %}
                    {% row 'justify-content-center m-2' %}
                      <a class="btn btn-dark w-50" href="#}">Detalhes</a>
                    {% endrow %}
                  {% endcol %}
                {% endrow %}
              </div>
            </div>
          {% endfor %}
        {% else %}
          <!-- Empty Context -->
          {% row 'd-flex justify-content-center mt-5' %}
            {% col 'col-md-8 my-2 text-center' %}
              <img src="{% static 'icons/cart-x.svg' %}" width="64" height="64" alt="Carrinho Vazio">         
              <h2 class="mt-2">Nenhum Pedido...</h2>
              <small>Faça seu primeiro pedido!</small>
            {% endcol %}
          {% endrow %}
          {% row 'd-flex justify-content-center mb-5' %}
            {% col 'col-md-8 my-2 text-center' %}
              <a class="btn btn-dark text-center w-50" href="{% url 'store:index' %}">Fazer Pedido</a>
            {% endcol %}
          {% endrow %}
        {% endif %}
      {% endcol %}
    {% endrow %}
  {% endcontainer %}
</section>
{% endif %}

{% endblock content %}